export interface ITiledMapData{
  compressionlevel:number,
  height:number,
  width:number,
  infinite:boolean,
  orientation:string,
  renderorder:string,
  tileheight:number,
  tilewidth:number,
  type:string,
  version:string, 
  layers:ILayerData[],
  tilesets:ITilesetData[],
}

export interface ITilesetData{
  columns:number,
  firstgid:number,
  image:string, 
  imageheight:number,
  imagewidth:number,
  margin:number,
  name:string, 
  spacing:number,
  tilecount:number,
  tileheight:number,
  tilewidth:number,
}
export interface ILayerData{
  id:number,
  data:Array<number>,
  height:number,
  width:number,
  opacity:number,
  name:string,
  type:string,
  visibility:boolean,
  x:number,
  y:number,
}